/*
   Name: Jude Hommel
   Date: 9-9-26
   Description: This program simulates and tracks multiple hot dog stands' monthly transactions
   Self-grade (0-100): 100

   IMPORTANT:
   - Any code submitted that is based on solutions from a previous semester will receive ZERO points.
   - Submissions must be your own original work.

   Testimony:
   I certify that all code submitted for this assignment is written by me, and I did not copy code from any person, website,
   or other resource.

   Signature/Name: Jude Hommel

   Reflection Questions (answer below):
   1) What two attributes did you add? Explain how each attribute is related to the HotDogStand class.
   I added a list of ratings and a number of employees, the average rating and the avg amount each employee sold is displayed once everything else is completed.
   2) What methods did you add? Explain how each method is related to the HotDogStand class.
   I added calculateAvgRating() and avgDogsSoldPerEmployee() which find the respective averages so they can be printed once the program finishes.

   -------------------------
   Sample Output (Example)
   -------------------------

   id#: 1192
   Owner: Gita
   Address: Folsom
   Hot dog sold: 4538     // Hot dogs sold in the last 30 days (generated by hotDogSold)
   income: 9076.0         // income for the last 30 days at this station
   _______________________________________________

   id#: 1057
   Owner: Gita
   Address: Rocklin
   Hot dog sold: 4513
   income: 9026.0
   _______________________________________________

   id#: 1902
   Owner: Gita
   Address: Sacramento
   Hot dog sold: 4852
   income: 9704.0
   ________________________________________________

   Total hotdogs sold at all the stations: 13903
   ________________________________________________
   Total income: 27806.0   // Total income from all three stations
   */

import java.util.ArrayList;

public class HotDogStandHommel
{
    // No code here
}

class HotDogStand
{
    // -------------------------
    // Static Variables
    // -------------------------
    private static double purchasePrice = 0.5;
    private static double soldPrice = 2;

    // -------------------------
    // Required Instance Variables
    // -------------------------
    private int id;
    private String owner;
    private String address;
    private int countSold;

    // -------------------------
    // Student-Added Variables (2 required)
    // -------------------------
    // These MUST be related to a hot dog stand (unrelated variables receive 0 points).
    private ArrayList<Integer> ratings = new ArrayList<Integer>();
    private int numEmployees;

	// -------------------------
    // Constructor
    // -------------------------
    // NOTE: Do not add a second constructor.
    public HotDogStand(int id, String owner, String address) 
    {
        this.id = id;
        this.owner = owner;
        this.address = address;
        this.ratings.add((int) (Math.random() * 5 + 1));
        this.numEmployees = (int) (Math.random() * 4) + 1;
    }

    // -------------------------
    // Getters
    // -------------------------
    public int getId()
    {
        return id;
    }
    public String getOwner()
    {
        return owner;
    }
    public String getAddress()
    {
        return address;
    }
    public int getCountSold()
    {
        return countSold;
    }
	public ArrayList<Integer> getRatings() {
		return ratings;
	}
	public int getNumEmployees() {
		return numEmployees;
	}

    // -------------------------
    // Setters
    // -------------------------
	public void setId(int id) {
		this.id = id;
	}
	public void setOwner(String owner) {
		this.owner = owner;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public void setCountSold(int countSold) {
		this.countSold = countSold;
	}
	public void setRatings(ArrayList<Integer> ratings) {
		this.ratings = ratings;
	}
	public void setNumEmployees(int numEmployees) {
		this.numEmployees = numEmployees;
	}


    /*
     * order(int count)
     * This method increases countSold by the parameter 'count'.
     */
    public void order(int count)
    {
        countSold += count;

        // Between 3-5 people give the stand a rating per month 
        for (int i = 0; i < (int) (Math.random() * 3) + 3; i++) 
        {
            ratings.add((int) (Math.random() * 5 + 1));
        }
    }

    /*
     * income()
     * This method calculates the income for the given station.
     * income = (soldPrice - purchasePrice) * countSold
     */
    public double calculateIncome()
    {
        return (soldPrice - purchasePrice) * countSold;
    }
    
    /*
     * toString()
     * This method returns a String representing this HotDogStand.
     * You MUST include your two added instance variables in the output.
     *
     * Sample format (use your variables):
     *
     * ID#: 661
     * Owner: Jose
     * Address: Rocklin
     * Hot dog sold: 330
     * Income: 660.0
     */
    public String toString()
    {
        return String.format(
            "ID#: %d%n" +
            "Owner: %s%n" +
            "Address: %s%n" +
            "Hot dog sold: %d%n" +
            "Number employees: %d%n" +
            "Income: %.2f%n" +
            "Rating: %.1f%n" +
            "Average hot dogs sold per employee: %.2f",
            id,
            owner,
            address,
            countSold,
            numEmployees,
            calculateIncome(),
            calculateAvgRating(),
            avgDogsSoldPerEmployee()
        );
    }

    /*
     * print()
     * This is a static method.
     * Use print/println to display helpful info related to this application.
     * You MUST call this method in YourDriver.
     */
    public static void print(HotDogStand[] stands)
    {
        int totalSold = 0;
        double totalIncome = 0;
        for (int i = 0; i < stands.length; i++)
        {
            System.out.println(stands[i].toString());
            System.out.println("_______________________________________________");
            totalSold += stands[i].getCountSold();
            totalIncome += stands[i].calculateIncome();
        }
        System.out.println("Total hotdogs sold at all the stations: " + totalSold);
        System.out.printf("Total income: %.2f%n", totalIncome);
    }

    // Calculates the average rating from the ArrayList ratings
    public double calculateAvgRating()
    {
        int total = 0;
        for (int i = 0; i<ratings.size(); i++) {
            total += ratings.get(i);
        }

        return (double) total / ratings.size();
    }



    // Calculates the average amount each employee sells per month
    public double avgDogsSoldPerEmployee()
    {
        return (double) countSold / numEmployees;
    }
}

/*
   Must complete this Driver for your code to be graded.
   Submissions without a completed YourDriver will NOT be graded.

   In this driver, you must:
   - Create three hot dog stands for yourself.
   - Generate three unique station IDs randomly (between min and max of your choice) using getRandNum().
   - Create three HotDogStand objects using those IDs.
   - Call hotDogSold() three times (once for each station) to compute hot dogs sold in the last 30 days.
   - Call order() for each stand using the generated sold count.
   - Compute and display:
 * total hot dogs sold at all stands
 * total income for all stands
 */
class YourDriver
{
    public static void main(String[] args)
    {
        int numStands = 3;
        int[] ids = new int[numStands];

        ids = getRandNum(0, 1000, numStands);
        String[] owners = { "Bill", "Tod", "Jessica" };
        String[] addresses = { "Rocklin", "The moon", "Nevada City" };

        HotDogStand[] stands = new HotDogStand[3];
        for (int i = 0; i < numStands; i++) {
            stands[i] = new HotDogStand(ids[i], owners[i], addresses[i]);

            stands[i].order(hotDogSold());
        }

        HotDogStand.print(stands);
    }

    /*
     * getRandNum(int min, int max)
     * Generates THREE unique random integers for station IDs.
     * Requirements:
     * - Declare an int array of size 3
     * - Generate and store 3 random numbers in the array
     * - If any two numbers match, keep generating until all three are unique
     * - Must use a while loop or do-while loop
     * Returns the array of three unique IDs.
     */
    public static int[] getRandNum(int min, int max, int arrSize)
    {
        int[] ids = new int[arrSize];

        for (int i = 0; i < arrSize; i++)
        {
            ids[i] = (int) (Math.random() * (max + 1 - min)) + min;


            boolean duplicate;
            do
            {
                duplicate = false;
                for (int j = 0; j < i; j++)
                {
                    if (ids[i] == ids[j]) 
                    {
                        ids[i] = (int) (Math.random() * (max + 1 - min)) + min;
                        duplicate = true;
                    }
                }
            } while (duplicate);
        }

        return ids;
    }

    /*
     * hotDogSold()
     * Calculates the number of hot dogs sold at one station in the last 30 days.
     *
     * Steps:
     * - Declare a variable to hold the monthly total
     * - Use a for-loop that runs 30 times (30 days)
     * - Each day generate a random number between 120 and 200 (hot dogs sold that day)
     * - Add each day's value to the total
     * - Return the total
     */
    public static int hotDogSold()
    {
        int total = 0;

        for (int i = 0; i < 30; i++) {
            total += (int) (Math.random() * 81) + 120;
        }

        return total;
    }
}

