/*
Name: Jude Hommel
Date: 9-9-26
Description: __________________________
Self-grade (0-100): ___________________

IMPORTANT:
- Any code submitted that is based on solutions from a previous semester will receive ZERO points.
- Submissions must be your own original work.

Testimony:
I certify that all code submitted for this assignment is written by me, and I did not copy code from any person, website,
or other resource.

Signature/Name: _______________________

Reflection Questions (answer below):
1) What two attributes did you add? Explain how each attribute is related to the HotDogStand class.
2) What methods did you add? Explain how each method is related to the HotDogStand class.

-------------------------
Sample Output (Example)
-------------------------

ID#: 1192
Owner: Gita
Address: Folsom
Hot dog sold: 4538     // Hot dogs sold in the last 30 days (generated by hotDogSold)
Income: 9076.0         // Income for the last 30 days at this station
_______________________________________________

ID#: 1057
Owner: Gita
Address: Rocklin
Hot dog sold: 4513
Income: 9026.0
_______________________________________________

ID#: 1902
Owner: Gita
Address: Sacramento
Hot dog sold: 4852
Income: 9704.0
________________________________________________

Total hotdogs sold at all the stations: 13903
________________________________________________
Total income: 27806.0   // Total income from all three stations
*/
import java.util.*;

public class HotDogStandHommel
{
   // No code here
}

class HotDogStand
{
   // -------------------------
   // Static Variables
   // -------------------------
   // TODO: declare a static variable to hold the PURCHASE price of a hotdog (cost to the stand)
   // TODO: declare a static variable to hold the SOLD price of a hotdog (price charged to customers)

   // -------------------------
   // Required Instance Variables
   // -------------------------
   // TODO: declare all required instance variables (ID, owner, address, countSold)

   // -------------------------
   // Student-Added Variables (2 required)
   // -------------------------
   // TODO: add TWO additional instance variables of your choice.
   // These MUST be related to a hot dog stand (unrelated variables receive 0 points).

   // -------------------------
   // Constructor
   // -------------------------
   // TODO: create the constructor and include your two added instance variables
   // NOTE: Do not add a second constructor.

   // -------------------------
   // Getters
   // -------------------------
   // TODO: create all getter methods for ALL instance variables (including your added ones)

   // -------------------------
   // Setters
   // -------------------------
   // TODO: create all setter methods for ALL instance variables (including your added ones)

   /*
    * order(int count)
    * This method increases countSold by the parameter 'count'.
    */
   // TODO: implement order method

   /*
    * income()
    * This method calculates the income for the given station.
    * Income = (soldPrice - purchasePrice) * countSold
    */
   // TODO: implement income method

   /*
    * toString()
    * This method returns a String representing this HotDogStand.
    * You MUST include your two added instance variables in the output.
    *
    * Sample format (use your variables):
    *
    * ID#: 661
    * Owner: Jose
    * Address: Rocklin
    * Hot dog sold: 330
    * Income: 660.0
    */
   // TODO: implement toString method

   /*
    * print()
    * This is a static method.
    * Use print/println to display helpful info related to this application.
    * You MUST call this method in YourDriver.
    */
   public static void print()
   {
      // TODO: implement
   }

   // TODO: Add method #1 (must use your added attribute(s))
   // Write a comment explaining what it does.
   
   

   // TODO: Add method #2 (must use your added attribute(s))
   // Write a comment explaining what it does.
}

/*
 Must complete this Driver for your code to be graded.
 Submissions without a completed YourDriver will NOT be graded.

 In this driver, you must:
 - Create three hot dog stands for yourself.
 - Generate three unique station IDs randomly (between min and max of your choice) using getRandNum().
 - Create three HotDogStand objects using those IDs.
 - Call hotDogSold() three times (once for each station) to compute hot dogs sold in the last 30 days.
 - Call order() for each stand using the generated sold count.
 - Compute and display:
     * total hot dogs sold at all stands
     * total income for all stands
*/
class YourDriver
{
   public static void main(String[] args)
   {
      // TODO: declare an int array of size 3 to hold IDs for three stands

      // TODO: call getRandNum(min, max) and store returned IDs in the array

      // TODO: declare and instantiate THREE HotDogStand objects

      // TODO: call hotDogSold() three times (once per station)

      // TODO: call order(...) on each stand using the corresponding sold count

      // TODO: compute total hot dogs sold using getCountSold() from each object

      // TODO: compute total income using income() from each object

      // TODO: display the output in the required format
   }

   /*
    * getRandNum(int min, int max)
    * Generates THREE unique random integers for station IDs.
    * Requirements:
    * - Declare an int array of size 3
    * - Generate and store 3 random numbers in the array
    * - If any two numbers match, keep generating until all three are unique
    * - Must use a while loop or do-while loop
    * Returns the array of three unique IDs.
    */
   public static int[] getRandNum(int min, int max)
   {
      // TODO: implement
      return null;
   }

   /*
    * hotDogSold()
    * Calculates the number of hot dogs sold at one station in the last 30 days.
    *
    * Steps:
    * - Declare a variable to hold the monthly total
    * - Use a for-loop that runs 30 times (30 days)
    * - Each day generate a random number between 120 and 200 (hot dogs sold that day)
    * - Add each day's value to the total
    * - Return the total
    */
   public static int hotDogSold()
   {
      // TODO: implement
      return 0;
   }

